export const projects = [
  {
    slug: 'itgreen-os',
    title: 'ITGREEN OS',
    eyebrow: 'Projet majeur de stage · 2026',
    category: 'Système métier',
    tier: 'flagship',
    featured: true,
    status: 'Déployé en contexte professionnel',
    summary: 'Un système Debian 12 qui réunit diagnostic matériel, effacement sécurisé et inventaire des ordinateurs reconditionnés.',
    context: 'ITGREEN reconditionne du matériel informatique. Les techniciens avaient besoin d’un outil unique pour contrôler les machines, sécuriser les données et fiabiliser leur entrée en stock.',
    need: 'Remplacer plusieurs manipulations dispersées par un parcours guidé, rapide et exploitable directement dans l’atelier.',
    role: 'Conception du système, intégration Debian, développement des scripts Python et réalisation d’une interface web adaptée au poste de diagnostic.',
    team: 'Projet mené durant mon stage chez ITGREEN, au contact des besoins réels de l’atelier.',
    duration: 'Stage de fin de BUT · 2026',
    stack: ['Debian 12', 'Python', 'Shell', 'Interface web', 'Diagnostic matériel', 'Effacement sécurisé'],
    challenges: [
      'Orchestrer plusieurs diagnostics et restituer les résultats dans une interface unique.',
      'Concevoir un parcours fiable pour l’effacement sécurisé des supports de stockage.',
      'Faire fonctionner une interface web dans un environnement système contraint et hors d’un usage web classique.'
    ],
    decisions: [
      'Choisir Debian 12 comme base stable et maîtrisable.',
      'Automatiser les opérations système avec des scripts Python dédiés.',
      'Utiliser une interface web locale pour livrer plus vite une expérience claire, maintenable et familière aux utilisateurs.'
    ],
    results: ['Diagnostic tout-en-un', 'Effacement sécurisé intégré', 'Inventaire centralisé', 'Parcours adapté à l’atelier'],
    images: [
      '/gallery/itgreendiagisoexemple vide.jpg',
      '/gallery/itgreen-anonymized/diagnostic-detail.png',
      '/gallery/itgreen-anonymized/diagnostic-table.png'
    ],
    mediaPending: false,
    confidentiality: 'Certaines informations resteront floutées à la demande d’ITGREEN. Les visuels publiés ne montreront aucune donnée sensible.',
    links: [],
    competencies: ['AC34.01', 'AC34.02', 'AC34.03', 'AC34.04', 'AC34.05', 'AC35.01', 'AC35.02', 'AC35.04'],
    ai: 'L’IA a pu accélérer la recherche et le diagnostic technique, sans recevoir de données internes. Les commandes, scripts et résultats ont été relus puis vérifiés sur les machines de test.',
    accent: '#ffd600'
  },
  {
    slug: 'itgreen-intranet',
    title: 'Intranet ITGREEN',
    eyebrow: 'Automatisation métier · 2026',
    category: 'Projet de stage',
    tier: 'flagship',
    featured: true,
    status: 'Développé en contexte professionnel',
    summary: 'Un intranet qui centralise le stock et rapproche eBay, Odoo et les opérations quotidiennes dans une même interface.',
    context: 'Une partie des tâches quotidiennes passait par plusieurs services et fichiers externes. Cette fragmentation ralentissait la mise en stock et le suivi commercial.',
    need: 'Réduire les doubles saisies et donner à l’équipe un point d’entrée unique pour les opérations les plus fréquentes.',
    role: 'Analyse des besoins, conception des parcours, développement des intégrations et automatisation des tâches métier.',
    team: 'Projet développé durant mon stage chez ITGREEN avec des retours directs des futurs utilisateurs.',
    duration: 'Stage de fin de BUT · 2026',
    stack: ['Application web', 'API eBay', 'Odoo', 'Gestion de stock', 'Automatisation'],
    challenges: [
      'Faire dialoguer des outils externes aux modèles de données différents.',
      'Rendre les opérations de stock plus rapides sans perdre en traçabilité.',
      'Transformer des habitudes métier en parcours courts et compréhensibles.'
    ],
    decisions: [
      'Centraliser les actions fréquentes dans l’intranet.',
      'Intégrer eBay pour limiter les allers-retours avec la plateforme.',
      'Rapprocher les fonctions Odoo et l’inventaire pour accélérer le processus de vente.'
    ],
    results: ['Moins de doubles saisies', 'Inventaire intégré', 'Actions eBay centralisées', 'Processus de vente raccourci'],
    images: [
      '/gallery/itgreen-anonymized/intranet-dashboard.png',
      '/gallery/itgreen-anonymized/intranet-ecommerce.png'
    ],
    mediaPending: false,
    confidentiality: 'Les comptes, indicateurs internes, données de stock et références commerciales ont été anonymisés directement dans les fichiers publiés.',
    links: [],
    competencies: ['AC34.01', 'AC34.02', 'AC34.04', 'AC34.05', 'AC35.01', 'AC35.02', 'AC35.04'],
    ai: 'Les usages éventuels de l’IA ont été limités à des données non sensibles. Chaque intégration a été testée à partir de cas métier réels et validée humainement.',
    accent: '#b7eb62'
  },
  {
    slug: 'geodevinette',
    title: 'GeoDevinette',
    eyebrow: 'Jeu web géographique · 2026',
    category: 'Projet personnel',
    tier: 'selected',
    featured: true,
    status: 'En ligne',
    summary: 'Un jeu inspiré de GeoGuessr qui invite à reconnaître un lieu depuis Street View puis à placer sa réponse sur la carte.',
    context: 'Le projet explore la géolocalisation ludique et l’intégration de services cartographiques dans une expérience web immédiatement compréhensible.',
    need: 'Créer une boucle de jeu fluide entre observation, déduction, choix sur la carte et révélation du résultat.',
    role: 'Conception du jeu, intégration des API Google et développement de l’interface.',
    team: 'Projet personnel.',
    duration: '2026',
    stack: ['Next.js', 'Google Maps API', 'Street View API', 'Google OAuth', 'Vercel'],
    challenges: ['Synchroniser Street View et la carte de réponse.', 'Gérer les états d’une partie sans casser le rythme.', 'Encadrer l’usage et les coûts des API Google.'],
    decisions: ['Séparer l’observation de la phase de réponse.', 'Donner un retour immédiat après chaque proposition.', 'Déployer une version accessible en ligne pour tester le parcours réel.'],
    results: ['Boucle de jeu fonctionnelle', 'Authentification Google', 'Déploiement public'],
    images: ['/gallery/geogeoingame.png', '/gallery/geogeoaccueil.png'],
    mediaPending: false,
    links: [{ label: 'Jouer à GeoDevinette', href: 'https://geogeo2.vercel.app/' }],
    competencies: ['AC34.01', 'AC34.03', 'AC34.04', 'AC34.05', 'AC35.02'],
    ai: 'L’IA a servi d’appui ponctuel pour explorer l’intégration des API. Les flux, quotas, erreurs et comportements de jeu ont été vérifiés dans l’application.',
    accent: '#6de6c2'
  },
  {
    slug: 'taskmaster',
    title: 'TaskMaster',
    eyebrow: 'Application full-stack · 2025',
    category: 'Projet universitaire',
    tier: 'selected',
    featured: true,
    status: 'Livré',
    summary: 'Une plateforme de gestion de projet inspirée de Trello et Jira, pensée pour coordonner des équipes en temps réel.',
    context: 'TaskMaster répond au besoin de centraliser les tâches, les sprints et les échanges d’une équipe dans un espace unique.',
    need: 'Concevoir une application complète, maintenable et immédiatement compréhensible par des utilisateurs habitués aux outils agiles.',
    role: 'Développement full-stack, conception des interfaces et intégration des interactions temps réel.',
    team: 'Projet réalisé en équipe dans le cadre du BUT MMI.',
    duration: 'Projet long · 2025',
    stack: ['Laravel', 'React', 'TypeScript', 'WebSocket', 'Tailwind'],
    challenges: ['Synchroniser les changements sans rechargement de page.', 'Structurer une interface dense tout en gardant les actions principales lisibles.', 'Gérer l’authentification et les droits d’accès.'],
    decisions: ['Séparer clairement API, logique métier et composants d’interface.', 'Utiliser des événements temps réel pour les tableaux partagés.', 'Construire des composants réutilisables pour les cartes, colonnes et états.'],
    results: ['Kanban et sprints fonctionnels', 'Authentification OAuth', 'Collaboration en temps réel'],
    images: ['/reference/showcase.png', '/reference/taskmaster1.png', '/reference/taskmaster2.png', '/reference/taskmaster3.jpeg', '/gallery/taskmasterfigma.png'],
    links: [{ label: 'Voir la démo', href: 'https://taskmaster.denizb.etu.mmi-unistra.fr/' }],
    competencies: ['AC34.01', 'AC34.02', 'AC34.04', 'AC34.05', 'AC35.02'],
    ai: 'L’IA a servi d’appui pour explorer des solutions, relire certains choix et accélérer le diagnostic. Chaque proposition a été relue, adaptée et testée avant intégration.',
    accent: '#9d5cff'
  },
  {
    slug: 'usine-a-chocolat',
    title: 'Usine à chocolat',
    eyebrow: 'Dispositif interactif · 2025',
    category: 'SAÉ collective',
    tier: 'selected',
    featured: true,
    status: 'Testé en conditions réelles',
    summary: 'Une application multi-stations qui permet aux visiteurs des JPO de commander puis suivre la fabrication de chocolats.',
    context: 'Le dispositif relie une interface web, plusieurs postes et une machine physique pendant une journée portes ouvertes.',
    need: 'Fluidifier le parcours de visiteurs nombreux tout en fiabilisant les commandes envoyées aux différentes stations.',
    role: 'Développement de l’application, logique des parcours, intégration des QR codes et suivi des états.',
    team: 'Projet collectif avec répartition des responsabilités et coordination régulière.',
    duration: 'SAÉ 5.01 · 2025',
    stack: ['Laravel', 'Livewire', 'Tailwind CSS', 'Vite', 'SQLite', 'QR Code'],
    challenges: ['Faire communiquer plusieurs stations autour d’une même commande.', 'Concevoir un parcours utilisable rapidement par un public de passage.', 'Prévoir les erreurs et reprises dans un contexte événementiel.'],
    decisions: ['Donner à chaque commande un QR code et un état explicite.', 'Adapter les interfaces aux responsabilités de chaque station.', 'Privilégier des retours visuels immédiats et des actions courtes.'],
    results: ['Parcours multi-stations', 'Suivi des commandes', 'Usage en contexte réel'],
    images: ['/reference/sae5012.png', '/reference/sae5013.png', '/reference/sae5014.png', '/reference/sae5015.png', '/gallery/usinea chocolat figma.png'],
    links: [{ label: 'Voir la démo', href: 'https://sae501-2.denizb.etu.mmi-unistra.fr/' }],
    competencies: ['AC34.02', 'AC34.03', 'AC34.05', 'AC35.01', 'AC35.02'],
    ai: 'Le workflow IA a été utilisé comme outil de recherche et de vérification, sans remplacer les tests sur le dispositif ni les décisions prises collectivement.',
    accent: '#ff9a3c'
  },
  {
    slug: 'counterlol',
    title: 'CounterLoL',
    eyebrow: 'Projet personnel · 2026',
    category: 'Produit personnel',
    tier: 'selected',
    featured: true,
    status: 'En ligne',
    summary: 'Un raccourci rapide et responsive pour retrouver un champion puis ouvrir son matchup sur U.GG.',
    context: 'Les joueurs consultent souvent les mêmes pages de statistiques avant une partie. CounterLoL réduit ce parcours à une recherche ou un filtre.',
    need: 'Permettre de retrouver un champion en quelques secondes, sur ordinateur comme sur mobile, sans reproduire les données de plateformes tierces.',
    role: 'Cadrage du besoin, direction visuelle, développement React, itérations avec l’IA et déploiement.',
    team: 'Projet personnel co-développé avec un assistant IA génératif, relu et piloté humainement.',
    duration: 'Prototype itératif · 2026',
    stack: ['React 19', 'TypeScript', 'Vite', 'Tailwind CSS', 'Motion', 'Vercel'],
    challenges: ['Afficher un grand catalogue sans perdre la rapidité de recherche.', 'Proposer filtres et favoris sans créer de compte utilisateur.', 'Rester transparent sur les sources Riot Games et U.GG.'],
    decisions: ['Conserver les préférences uniquement dans le navigateur avec localStorage.', 'Rediriger vers la source U.GG au lieu de copier ses statistiques.', 'Charger progressivement les images via Riot Data Dragon.'],
    results: ['Recherche instantanée', 'Filtres par rôle', 'Favoris locaux', 'Déploiement Vercel'],
    images: ['/gallery/counterlol.png'],
    links: [{ label: 'Ouvrir CounterLoL', href: 'https://counterlol.vercel.app/' }],
    competencies: ['AC34.01', 'AC34.05', 'CE4.03', 'CE4.04', 'CE5.01', 'CE5.03', 'CE5.04'],
    ai: 'Le besoin et les critères ont été définis en amont. L’IA a proposé une première base, ensuite relue, corrigée, simplifiée et testée.',
    accent: '#f4f4f4'
  },
  {
    slug: 'evolve2d',
    title: 'Evolve2D',
    eyebrow: 'Jeu idle 2D · En développement',
    category: 'Laboratoire personnel',
    tier: 'lab', featured: false, status: 'Prototype en cours',
    summary: 'Une réinterprétation visuelle du jeu Evolve avec une interface plus accessible, des éléments 2D et un univers narratif.',
    context: 'Evolve repose surtout sur du texte. Ce projet explore comment rendre ses systèmes plus lisibles pour un nouveau public sans perdre leur profondeur.',
    need: 'Construire une progression claire, donner une présence visuelle aux ressources et introduire le joueur sans le submerger.',
    role: 'Direction du produit, UI/UX, game design, développement et écriture du lore.',
    team: 'Projet personnel en cours.', duration: '2026 · En développement',
    stack: ['Jeu 2D', 'UI/UX', 'Game design', 'Lore'],
    challenges: ['Rendre des systèmes complexes progressivement lisibles.', 'Créer une identité visuelle cohérente pour un idle game.', 'Équilibrer fidélité à l’inspiration et proposition personnelle.'],
    decisions: ['Ajouter une progression visuelle au lieu d’un écran uniquement textuel.', 'Introduire les mécaniques par étapes.', 'Relier la progression à un récit original.'],
    results: ['Direction produit définie', 'Prototype en cours', 'Système narratif en conception'],
    images: ['/gallery/evolve2d village amélioré .png', '/gallery/evolve2dbase.png', '/gallery/evolve2dportals.png', '/gallery/evolve2dspace.png'], mediaPending: false,
    links: [{ label: 'Découvrir le jeu d’origine', href: 'https://pmotschmann.github.io/Evolve/' }],
    competencies: ['AC34.01', 'AC34.03', 'AC35.03'], ai: 'L’IA peut soutenir l’exploration technique et la cohérence du lore. Les mécaniques, l’équilibrage et la direction artistique restent des décisions de conception.', accent: '#ef8bff'
  },
  {
    slug: 'trk-lol',
    title: 'trk.lol',
    eyebrow: 'Produit data · En pause active',
    category: 'Laboratoire personnel', tier: 'lab', featured: false, status: 'Ambition conservée, priorité réduite',
    summary: 'Un tracker League of Legends ambitieux, mis en retrait le temps de mieux maîtriser les API Riot et de trouver un angle réellement différenciant.',
    context: 'Le marché des trackers est très concurrentiel. Le projet demande plus qu’une interface : il faut une proposition claire, des données fiables et une vraie capacité de maintenance.',
    need: 'Identifier une valeur spécifique avant d’investir davantage dans un produit data coûteux à construire et à maintenir.',
    role: 'Recherche produit, exploration des API, conception et développement.', team: 'Projet personnel.', duration: 'Projet long · En pause active',
    stack: ['Riot Games API', 'Données de jeu', 'Product design', 'Data visualisation'],
    challenges: ['Se différencier de produits établis.', 'Transformer beaucoup de données en décisions utiles.', 'Dimensionner le projet de façon réaliste.'],
    decisions: ['Ne pas surproduire un clone sans valeur propre.', 'Faire de Zen LoL un terrain d’apprentissage plus ciblé.', 'Conserver les acquis techniques pour une reprise future.'],
    results: ['Analyse concurrentielle', 'Périmètre réévalué', 'Feuille de route recentrée'],
    images: ['/gallery/trklolaccueil.png', '/gallery/trklolcompteoverview.png', '/gallery/trklol detailmatch.png', '/gallery/trklolstatistyique.png', '/gallery/trklolmetadetft.png', '/gallery/trklol tracker valorant compte.png', '/gallery/trklol valorant match detail.png', '/gallery/trklol figma .png'], mediaPending: false, links: [],
    competencies: ['AC34.01', 'AC35.01', 'AC35.02'], ai: 'L’IA aide à explorer des hypothèses, mais la viabilité dépend surtout de la recherche utilisateur, de la qualité des données et d’un positionnement différenciant.', accent: '#68a6ff'
  },
  {
    slug: 'zen-lol',
    title: 'Zen LoL',
    eyebrow: 'Application desktop · En développement',
    category: 'Laboratoire personnel', tier: 'lab', featured: false, status: 'Prototype en cours',
    summary: 'Une application Tauri qui suit l’humeur du joueur pour prévenir la frustration et l’escalade émotionnelle pendant les sessions.',
    context: 'Après trk.lol, ce projet recentre l’exploration des API Riot sur un besoin plus atteignable et moins couvert par les outils existants.',
    need: 'Aider le joueur à reconnaître les signaux de frustration et à prendre du recul avant que la session ne se dégrade.',
    role: 'Cadrage produit, conception de l’expérience, développement desktop et exploration des API Riot.', team: 'Projet personnel.', duration: '2026 · En développement',
    stack: ['Tauri', 'Riot Games API', 'Application desktop', 'Suivi d’humeur'],
    challenges: ['Suivre l’état émotionnel sans être intrusif.', 'Formuler des recommandations utiles sans médicaliser l’expérience.', 'Relier les sessions de jeu et les retours déclaratifs avec transparence.'],
    decisions: ['Privilégier un suivi volontaire et local.', 'Employer un vocabulaire centré sur la frustration et la concentration.', 'Utiliser ce projet comme étape concrète vers une meilleure maîtrise des API Riot.'],
    results: ['Positionnement défini', 'Architecture Tauri explorée', 'Prototype en développement'],
    images: ['/gallery/zenlolaccueil.png', '/gallery/zenlol parametre.png', '/gallery/zenlolentrainement.png'], mediaPending: false, links: [],
    competencies: ['AC34.01', 'AC34.04', 'AC35.01', 'AC35.03'], ai: 'L’IA peut aider à prototyper et reformuler les interactions. Les recommandations doivent rester prudentes, explicables et testées auprès de joueurs.', accent: '#b7eb62'
  },
  {
    slug: 'new-horizon',
    title: 'New Horizon',
    eyebrow: 'Projet de stage · 2025',
    category: 'Projet de stage',
    tier: 'archive',
    featured: false,
    status: 'Mis en ligne',
    summary: 'Une plateforme associative réalisée durant mon stage, pour présenter les actions, membres, événements et dons de New Horizon.',
    context: 'New Horizon avait besoin d’un site clair et administrable pour structurer sa présence en ligne et valoriser ses actions auprès du public.',
    need: 'Créer une plateforme moderne, maintenable et suffisamment complète pour regrouper présentation, contenus associatifs, événements et parcours de donation.',
    role: 'Développement full-stack, intégration des interfaces, structuration des données et déploiement du site pendant mon stage.',
    team: 'Projet réalisé en stage, avec des retours liés aux besoins réels de l’association.',
    duration: 'Stage · 2025',
    stack: ['Next.js', 'React', 'Prisma', 'Supabase', 'PostgreSQL', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    challenges: [
      'Structurer plusieurs types de contenus associatifs dans une interface cohérente.',
      'Prévoir une base de données adaptée aux membres, événements et donations.',
      'Livrer une plateforme présentable en ligne dans un cadre de stage.'
    ],
    decisions: [
      'Utiliser Next.js et React pour construire une interface rapide et maintenable.',
      'Centraliser les données avec Prisma et Supabase.',
      'Déployer sur Vercel pour obtenir une mise en ligne simple et fiable.'
    ],
    results: ['Site associatif mis en ligne', 'Architecture full-stack', 'Base de données structurée', 'Projet réalisé en contexte professionnel'],
    images: ['/reference/new-horizon.png', '/reference/newhorizon4.png', '/reference/newhorizon2.png', '/reference/newhorizon3.png'],
    links: [{ label: 'Voir le projet', href: 'https://new-horizon-blond.vercel.app/' }],
    competencies: ['AC34.01', 'AC34.02', 'AC34.05', 'AC35.01', 'AC35.02', 'AC35.04'],
    ai: 'L’IA a pu servir d’appui ponctuel pour explorer des pistes techniques ou reformuler certains contenus. Les choix d’architecture, l’intégration et la validation sont restés pilotés humainement.',
    accent: '#5d7cff'
  },
  {
    slug: 'jeu-course-unity',
    title: 'Speedzone V2',
    eyebrow: 'Jeu vidéo Unity · 2024',
    category: 'Jeu vidéo Unity',
    tier: 'archive',
    featured: false,
    status: 'Prototype jouable',
    summary: 'Un jeu de course local à deux joueurs développé avec Unity et C#, présenté directement avec sa vidéo de gameplay.',
    context: 'Le projet explore la création d’un jeu de course compétitif en écran partagé, avec une boucle simple : départ, tours, vitesse et confrontation directe.',
    need: 'Produire un prototype jouable qui démontre la gestion des véhicules, de la caméra, de l’interface et du rythme de course.',
    role: 'Développement Unity/C#, intégration du gameplay, réglage des contrôles et mise en place de l’interface de course.',
    team: 'Projet réalisé dans un cadre académique.',
    duration: '2024',
    stack: ['Unity', 'C#', 'Game design', 'Split-screen', 'Prototype jouable'],
    challenges: [
      'Gérer deux joueurs simultanément sur un même écran.',
      'Rendre la conduite lisible et réactive malgré un prototype rapide.',
      'Afficher les informations de course sans gêner la visibilité.'
    ],
    decisions: [
      'Utiliser un écran partagé pour garder une confrontation locale directe.',
      'Prioriser une boucle de gameplay simple plutôt qu’un contenu trop large.',
      'Documenter le projet avec une vidéo intégrée plutôt qu’un lien externe.'
    ],
    results: ['Prototype jouable', 'Course locale à deux joueurs', 'Interface de tours et vitesse', 'Vidéo de gameplay intégrée'],
    images: ['/reference/speedzonev2-01.jpg', '/reference/speedzonev2-02.jpg', '/reference/speedzonev2-03.jpg'],
    video: '/reference/unity-racing.mp4',
    links: [],
    competencies: ['AC34.03', 'AC35.02'],
    ai: 'Ce projet sert surtout de preuve Unity/C# et gameplay. L’IA n’a pas été centrale : la validation repose principalement sur le test du prototype et l’observation du gameplay.',
    accent: '#4c86ff'
  },
  { slug: 'ecostay', title: 'Ecostay Global', eyebrow: 'E-commerce · 2023', category: 'Archive', tier: 'archive', featured: false, summary: 'Un site vitrine et e-commerce réalisé avec WordPress et WooCommerce.', stack: ['WordPress', 'WooCommerce', 'PHP'], images: ['/gallery/ecostay.png'], links: [], accent: '#47b477' },
  { slug: 'green-life', title: 'Green Life', eyebrow: 'Shopify · 2023', category: 'Archive', tier: 'archive', featured: false, summary: 'Une boutique Shopify responsive dédiée à des solutions écologiques.', stack: ['Shopify', 'Liquid', 'JavaScript'], images: ['/gallery/greenlife.png'], links: [], accent: '#79b841' }
];

export const flagshipProjects = projects.filter((project) => project.tier === 'flagship');
export const featuredProjects = projects.filter((project) => project.featured);
export const labProjects = projects.filter((project) => project.tier === 'lab');
export const archivedProjects = projects.filter((project) => project.tier === 'archive');
export const getProjectBySlug = (slug) => projects.find((project) => project.slug === slug);
